### ISSUE TITLE
Document traits/usb/root_overlay

### ISSUE THREAD

**Issue by probonopd** [krebscode/minikrebs#4]
A README would be great. How do I use this? Does this automatically format a USB stick or does it expect it to be pre-formatted? The fstab also contains a section about swap?

**Comment by makefu** [comment]
Sorry for the late follow-up (2 years late in fact). i am not sure if it is even relevant anymore.
I will document the usage but the basic idea is that the usb-stick is mounted correctly before building.

**Comment by probonopd** [comment]
Yes, I'd still be interested in how to use this since the 4 MB built-in flash can become very scarce.
